##### IE531: Algorithms for Data Analytics #
## &copy;  [Professor Ramavarapu "RS" Sreenivas](http://rsree.ise.illinois.edu) ##
### Industrial and Enterprise Systems Engineering, The Grainger College of Engineering,  UIUC ###

<hr style="border:2px solid blue"> </hr>

## Programming Assignment 3:  Finding a Representative Data Vector for a Collection of Data Vectors via Norm Minimization ## 
## Due Date: March 10, 2023 ##

***

In HW2 you showed that the <i>Norm-Minimization Problem</i> is a special case of <i>Semidefinite Programming</i>. You were introduced to an SDP-solver called <tt>cvxpy</tt> in Lesson 1. More specifically, you showed that the <i>Norm-Minimization Problem</i> is an instance of <i>Second-Order Cone Programming</i> (SOCP), which in turn is a special case of an SDP. At this link ![https://www.cvxpy.org/examples/basic/socp.html] you will find the syntax that will let you use <tt>cvxpy</tt> to solve an SOCP-instance. 

In this programming assignment, you are given a random collection of data-vectors $\{{\bf b}_i\}_{i=1}^m$, where $\forall i, {\bf b}_i \in \mathcal{R}^d$. The objective is find a representative <i>d</i>-dimensional data vector ${\bf y} \in \mathcal{R}^d$, that solves
$$
\min_{\bf y} \left\{
\max_{i \in \{1, 2, \ldots, m\}} \| {\bf y} - {\bf b}_i \|
\right\}.
$$


### Programming Assignment ###

You are going to augment the Python Code shown below that solves the above problem. Try a couple of different values for <i>d</i> and <i>m</i>. You may/may-not get the same results as me... just saying!

I am looking for something along the lines of the figure shown below (for different values for <i>d</i> and <i>m</i>)

<table><tr>
<td> 
  <p align="center">
    <img alt="Routing" src="Figures/fig1.pdf">
    <br>
    <em style="color: grey">Figure 1: Sample Output.
</em>
  </p> 
</td>
</tr></table>
***

In [1]:
# IE531: Algorithms for Data Analytics
#
# Hint in the form of a Jupyter Notebook for Programming Assignment 2
#
#
import cvxpy as cp
import numpy as np

In [2]:
# The names of the variables are self-explanatory
#
no_of_data_vectors = 3
data_dimension = 5
data_matrix = np.random.rand(data_dimension, no_of_data_vectors)
print(data_matrix)

[[0.93158616 0.21836496 0.25067286]
 [0.07378263 0.25377295 0.9591974 ]
 [0.21820484 0.59932053 0.08499067]
 [0.92976128 0.65061737 0.94230923]
 [0.00163542 0.38348864 0.86095751]]


In [16]:
## FILL THIS PART
#
# Look at the example in https://www.cvxpy.org/examples/basic/socp.html that solves
# an SOCP-instance... make relevant changes/modifications to this example to solve 
# the norm-minimization problem defined above
#
t = cp.Variable()
y = cp.Variable(data_dimension)

objective=cp.Minimize(t)
soc_constraints = [cp.SOC(t, y - data_matrix[:,i]) for i in range(no_of_data_vectors)]

prob = cp.Problem(objective, soc_constraints)
prob.solve()


x= cp.hstack([t,y])



[0.70780297 0.59113161 0.5164912  0.15159544 0.93603674 0.43129653]


In [11]:
# Print result... see https://www.cvxpy.org/examples/basic/socp.html 
# 
print ("Data Dimension: ", data_dimension)
print ("Number of Data-Vectors: ", no_of_data_vectors)
print ("The optimal value is", prob.value)
print ("A solution x is")
print (x.value)

Data Dimension:  5
Number of Data-Vectors:  3
The optimal value is 0.7078029669886663
A solution x is
[0.70780297 0.59113161 0.5164912  0.15159544 0.93603674 0.43129653]


In [12]:
# Verification..
solution = np.zeros(data_dimension)
for i in range(data_dimension) :
    solution[i] = x.value[i+1]
print ("Representative Vector:")
print (solution)
print ("Norm of the representative vector: ", np.linalg.norm(solution))
print ("Verification: ")
for i in range(no_of_data_vectors) :
    print (np.linalg.norm(solution - data_matrix[:,i]))

Representative Vector:
[0.59113161 0.5164912  0.15159544 0.93603674 0.43129653]
Norm of the representative vector:  1.30436283158974
Verification: 
0.7078029682412825
0.7015578474408991
0.7078029677067459
